### ISSUE TITLE
Fix bson thing

### ISSUE THREAD

**Issue by MillerJL** [MillerJL/NSABot_api#1]
Getting the following error on initial execution

```
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/johnmiller/Dev/test/NSABot_api/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

Everything works fine after that error message, but it should still be resolved

**Comment by MillerJL** [comment]
In node_modules/mongodb/node_modules/bson/ext/index.js

Code looks for windows version of stuff, but obviously doesn't exist cause mac so error message pops out. That portion of code just spits out error messages so you could just delete the portions of code that spit out error message if you wanted to.

**Comment by MillerJL** [comment]
No longer an issue after switch to rethinkdb
